version: 2
builds:
  - id: lazyworktree
    env:
      - CGO_ENABLED=0
    main: ./cmd/lazyworktree
    binary: lazyworktree
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -w
      - -s
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser
archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE
      - README.md
      - config.example.yaml
homebrew_casks:
  - name: lazyworktree
    repository:
      owner: chmouel
      name: lazyworktree
    directory: Casks
    homepage: "https://github.com/chmouel/lazyworktree"
    description: "lazyworktree - A TUI tool to manage git worktrees"
    dependencies:
      - formula: git
      - formula: git-delta
      - formula: lazygit
      - formula: less
      - formula: tmux
snapshot:
  version_template: "{{ .Tag }}-next"

release:
  prerelease: "false"

checksum:
  name_template: "checksums.txt"

nfpms:
  - file_name_template: "{{ .ConventionalFileName }}"
    homepage: https://github.com/chmouel/lazyworktree
    description: "lazyworktree - A TUI tool to manage git worktrees"
    maintainer: Chmouel Boudjnah <chmouel@chmouel.com>
    license: Apache 2.0
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/bin
    dependencies:
      - git
      - git-delta
      - lazygit
      - less
      - tmux
    contents:
      - src: config.example.yaml
        dst: /usr/share/doc/lazyworktree/config.example.yaml
    overrides:
      deb:
        dependencies:
          - git
          - git-delta
          - lazygit
          - less
          - tmux
      rpm:
        dependencies:
          - git
          - git-delta
          - lazygit
          - less
          - tmux
      apk:
        dependencies:
          - git
          - delta
          - lazygit
          - less
          - tmux
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^Brew formula update"
      - Merge pull request
      - Merge branch
      - go mod tidy
      - Update README.md
      - Update coverage badge
      - Brew cask update

universal_binaries:
  - ids:
      - lazyworktree
    replace: true

aurs:
  - name: lazyworktree-bin
    homepage: "https://github.com/chmouel/lazyworktree"
    description: "lazyworktree - A TUI tool to manage git worktrees"
    maintainers:
      - "Chmouel Boudjnah <chmouel@chmouel.com>"
    license: Apache 2.0
    private_key: "{{ .Env.AUR_PRIVATE_KEY }}"
    git_url: ssh://aur@aur.archlinux.org/lazyworktree-bin.git
    depends:
      - git
      - delta
      - lazygit
      - less
      - tmux
    package: |-
      # bin
      install -Dm755 "./lazyworktree" "${pkgdir}/usr/bin/lazyworktree"

      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/lazyworktree/LICENSE"

      # config example
      install -Dm644 "./config.example.yaml" "${pkgdir}/usr/share/doc/lazyworktree/config.example.yaml"
