# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyworktree" do
  name "lazyworktree"
  desc "lazyworktree - A TUI tool to manage git worktrees"
  homepage "https://github.com/chmouel/lazyworktree"
  version "1.15.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazyworktree"
  depends_on formula: [
      "git",
      "git-delta",
      "lazygit",
      "less",
      "tmux",
    ]

  on_macos do
    url "https://github.com/chmouel/lazyworktree/releases/download/v#{version}/lazyworktree_Darwin_all.tar.gz"
    sha256 "6d5f1fff3bd243565f15e375025230403f871d989e3c9f5d7099a9e6f69c2cf4"
  end

  on_linux do
    on_intel do
      url "https://github.com/chmouel/lazyworktree/releases/download/v#{version}/lazyworktree_Linux_x86_64.tar.gz"
      sha256 "336877dbb66d0c578010486fc569b2d72102825011b24dcafdd4a83ff88a31ac"
    end
    on_arm do
      url "https://github.com/chmouel/lazyworktree/releases/download/v#{version}/lazyworktree_Linux_arm64.tar.gz"
      sha256 "8ba9f076f5b47cf385b52c68a30c52963adcaa14d675974018450496b1781eab"
    end
  end

  # No zap stanza required
end
